# Generated by Django 3.0.7 on 2020-07-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTSWebsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='description',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
    ]
