# Generated by Django 3.0.7 on 2020-07-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTSWebsite', '0003_remove_album_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DTSWebsite.Album'),
        ),
    ]
